<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_GrammaticalFeaturesToLanguages extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'grammatical_features_to_languages', array('grammatical_feature_id','language_id','source'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getGrammatical_feature_id() { return $this->fields["grammatical_feature_id"]; }
    public function getLanguage_id() { return $this->fields["language_id"]; }
    public function getSource() { return $this->fields["source"]; }
}