<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_GrammaticalFeatureCategoryHeirarchies extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'grammatical_feature_category_heirarchies', array('parent_id','child_id','distance'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getParent_id() { return $this->fields["parent_id"]; }
    public function getChild_id() { return $this->fields["child_id"]; }
    public function getDistance() { return $this->fields["distance"]; }
}